### ISSUE TITLE
Pastebin on the Emabssy

### ISSUE THREAD

**Issue by MattDHill** [mkaczanowski/pastebin#13]
Hi, the contact form on your website is broken, and we couldn't find another way to reach you.

Just wanted to let you know we will be releasing Pastebin as a one-click install to the Embassy personal server tomorrow or Wednesday and giving you a personal shout-out. Soon Hundreds, and then thousands, of users will, with the click of a button, be running Pastebin over Tor V3 on a physical device in their own home. As an icon, we are using a higher resolution version of the site's favicon. If you prefer something else, please let us know ASAP. We will be posting issues and feature requests in Github as they arise from our users, and we will contribute to the project or fork it as needed. Thank for building cool software!

**Comment by mkaczanowski** [comment]
Hi there!

> Hi, the contact form on your website is broken, and we couldn't find another way to reach you.
Ugh, lemme fix that :)

> Just wanted to let you know we will be releasing Pastebin as a one-click install to the Embassy personal server tomorrow or Wednesday and giving you a personal shout-out.
Nice! It's great that people find this project useful (as I do)

> As an icon, we are using a higher resolution version of the site's favicon.
That's cool with me

> We will be posting issues and feature requests in Github as they arise from our users, and we will contribute to the project or fork it as needed
Cool, I am happy to fix any upcoming issues (or review PR's). It would be great to one stable repo, so feel welcome to share feedback (hopefully no forks would be needed)

Great news, thanks for sharing!
