### ISSUE TITLE
API documentation?

### ISSUE THREAD

**Issue by MacGyver27** [mkaczanowski/pastebin#16]
Hi,

Does this have a public API ? I would like to integrate it into automated process and trying to find docs for its REST API.

Thanks, Michal

**Comment by mkaczanowski** [comment]
Hey @MacGyver27,

while there is no official API versioning etc (aka API might change in the future), I updated the documentation to reflect the current state: https://github.com/mkaczanowski/pastebin/blob/master/API.md

**Comment by MacGyver27** [comment]
Thanks, will try.
