### ISSUE TITLE
Altering index.html

### ISSUE THREAD

**Issue by MacGyver27** [mkaczanowski/pastebin#17]
Hi,

I wanted to change the page layout from `container-fluid` to `container` but I can't seem to figure out how and from where is the static page served. I see in docs you mention they are completely served from memory, but they have to be pulled from somewhere..

Thanks, Michal

**Comment by mkaczanowski** [comment]
Hi,

so the template file is here: https://github.com/mkaczanowski/pastebin/blob/master/static/index.html
It gets compiled into the binary as a slice of bytes / array. Then a REST HTTP call renders that template and sends the HTTP Response.

So, to modify the index.html you should look into the /static/index.html and the code that renders that template
