### ISSUE TITLE
Remove expiration times

### ISSUE THREAD

**Issue by tyler71** [mkaczanowski/pastebin#2]
Is it possible to limit the available paste expiration times?
For example, removing `Expires: Never` option.
Having the ability to change the default would be great as well

**Comment by mkaczanowski** [comment]
> Is it possible to limit the available paste expiration times?

Just click on the dropdown menu :) 

![image](https://user-images.githubusercontent.com/4912567/89232273-63fe6700-d5e7-11ea-947e-7ee557fdb44e.png)

**Comment by mkaczanowski** [comment]
> Having the ability to change the default would be great as well

that is not configurable now, however PR's are welcome
