### ISSUE TITLE
how to put static resources on my self-built server

### ISSUE THREAD

**Issue by jingtaozhang18** [mkaczanowski/pastebin#20]
I use the docker image on dockerhub to deploy my service. But getting static resource through cdnjs.cloudflare.com is relatively slow for me. So Is there an easy way to put static resources on my self-built server?

**Comment by mkaczanowski** [comment]
atm you could modify the urls here:
https://github.com/mkaczanowski/pastebin/blob/a8e8476c9c25575d5f8a29431bff3d4d5459ac0c/src/plugins.rs#L15

but it's not configurable from the CLI

**Comment by jingtaozhang18** [comment]
Thanks for your help!
