### ISSUE TITLE
ARM docker hub images ?

### ISSUE THREAD

**Issue by Mrfork91** [mkaczanowski/pastebin#21]
Hello, 
At the link [https://hub.docker.com/r/mkaczanowski/pastebin/tags?page=1&ordering=last_updated](https://hub.docker.com/r/mkaczanowski/pastebin/tags?page=1&ordering=last_updated)  there aren't ARM arch images, even where the overview says: 

ARM images:
docker pull mkaczanowski/pastebin:armv7
docker pull mkaczanowski/pastebin:armv8

Is it a mistake ? , Can you check OS/ARCH build ?
I want to try it on a raspberry pi, but first say -Thanks for all, great work with this project -

**Comment by mkaczanowski** [comment]
the image is not marked with proper arch, though the binary within the image (armv7, armv8) is compiled for arm
