### ISSUE TITLE
Adding line count when viewing a paste

### ISSUE THREAD

**Issue by SuperFola** [mkaczanowski/pastebin#22]
Hi there,

I searched but didn't find what I was looking for, is this possible to display the line count when viewing a paste?

Currently it looks like that:
![image](https://user-images.githubusercontent.com/10694085/112303194-5132c280-8c9c-11eb-81af-8dbb499bf3f7.png)

Thanks in advance

**Comment by lenaxia** [comment]
This is definitely an important feature I'd like to see added.

**Comment by mkaczanowski** [comment]
Now you can use `--ui-line-numbers` to enable enumeration in `prism.js`.

https://github.com/mkaczanowski/pastebin/commit/93564547d29e7377e5d1575f30a00a8dd3dde357
