### ISSUE TITLE
Paste is vulnerable to XSS

### ISSUE THREAD

**Issue by SuperFola** [mkaczanowski/pastebin#23]
see https://paste.12f.pl/ckCJatzmaEmb

I just wrote `<script>alert("ok")</script>`

**Comment by mkaczanowski** [comment]
Yeah, that needs to be addressed soon (PR's are most welcome)

**Comment by erkiesken** [comment]
Just made a PR. I hope the javascript plugin output loop was the only place needing special raw output. If you know other template sections that need this, then let me know.

**Comment by erkiesken** [comment]
@mkaczanowski any chance you can review, merge and release this fix?
