### ISSUE TITLE
Is there a way to view previously created pastes?

### ISSUE THREAD

**Issue by lenaxia** [mkaczanowski/pastebin#25]
Specifically looking to manage old pastes to prevent a buildup of data.

Or do I need to wipe my --db folder in order to clear old pastes?

**Comment by mkaczanowski** [comment]
If a pastebin has an expiry time, then it'll be automatically pruned. 

> Is there a way to view previously created pastes
Pastes are stored in the rocks db (--db) and there is some ldb cli available here: https://github.com/facebook/rocksdb/tree/master/tools you can use it to navigate through database
