### ISSUE TITLE
Ctrl+C not working

### ISSUE THREAD

**Issue by ronhanson** [mkaczanowski/pastebin#29]
Hi,
When running the docker image like : 

`docker run --network host -it mkaczanowski/pastebin --port 8082`

It seems not to respond to SIGINT / Ctrl+C signal, despite the fact rocket `ctrlc` parameter is set to default.

Note : running the app on Docker for Mac. Maybe related to the fact it does not serve anything or does not seem to work on a Mac.

**Comment by arielb2** [comment]
Hi @ronhanson, try "docker kill signal=SIGINT container_name" (control + c), or docker run -it ....., this allows to do a ctrl p + ctrl q

**Comment by mkaczanowski** [comment]
This works:
```
docker run --init --network host -it mkaczanowski/pastebin --port 8082
```
