### ISSUE TITLE
Link to paste  doesn't include uri-prefix

### ISSUE THREAD

**Issue by IvoPo** [mkaczanowski/pastebin#32]
Hi there,

when i paste a new note, the msg  _The paste has been successfully created:_ with the URL to the paste, does not include the uri-prefix.

i'm running docker-image:latest with:
_--address 0.0.0.0 --port 8000 --uri="TLD" --uri-prefix="/pastebin" --db=/var/lib/pastebin/ --plugins prism mermaid_

o/

**Comment by arielb2** [comment]
Hi @IvoPo.

try this --uri="http://fqdn/pastebin"

**Comment by IvoPo** [comment]
hmm, it didn't work with only --uri before. Now i'm using --uri=https://TLD/pastebin --uri-prefix="/pastebin" and it seems to work fine now, thanks
