### ISSUE TITLE
Password Enter key defaults to the Close button

### ISSUE THREAD

**Issue by akzkak** [mkaczanowski/pastebin#34]
Type password and hit enter key will close and open window with a blank text field. To get in you have to enter password and click on blue Decrypt button with mouse for it to work. (or tap, tap enter)

Would love to see this fixed. Little thing, but enough to confuse people especially for the non tech savvy.

**Comment by mkaczanowski** [comment]
will look into this. Thanks for reporting the issue :+1:

**Comment by aronmgv** [comment]
@mkaczanowski any ETA please? Thanks!
